# Maestría en Controles Industriales
### Entregable 1: Introducción a Numpy
### Autor: Diego Andres Rojas Gonzalez
### Docente: Dr. Oscar J. Suarez
### Matemática Aplicada
### Universidad de Pamplona

# Introducción a manejo de vectores y matrices con Numpy

En este tutorial aprenderemos a realizar operaciones básicas de algebra lineal usando la libreria Numpy de Python

## 1.- Importar libreria Numpy

Numpy es una librería desarrollada para Python que permite crear arreglos y hacer operaciones algebraícas de manera muy sencilla. 

In [1]:
#importamos numpy
import numpy as np

## 2.- Creación de arreglos con Numpy

Se pueden crear arreglos en numpy haciendo uso de la clase array() de numpy

In [2]:
#Crea un vector fila
v = np.array([35, 2, 20, 7])

#imprimir el arreglo y el tamaño
print(v)
print("=====================================")
print(f"El tamaño de v es: {v.shape}")

#Crear una matriz de 3x3
A = np.array([[3, -8, 5], 
              [17, 10, 52], 
              [1, 5, 12]])
print("=====================================")
print(A)
print("=====================================")
print(f"El tamaño de A es:{A.shape}")
print(f"El tamaño de A es:" + str(A.shape))

[35  2 20  7]
El tamaño de v es: (4,)
[[ 3 -8  5]
 [17 10 52]
 [ 1  5 12]]
El tamaño de A es:(3, 3)
El tamaño de A es:(3, 3)


La clase array posee varios métodos que permiten hacer operaciones sencillas sobre los arreglos, así como consultar o sustituir sus elementos.

In [3]:
#Consultar elementos de la matriz
print("=====================================")
print("La posición de la matriz A[2,2] = " + str(A[2,2]))
print("=====================================")
print("La posición de la matriz A[0,0] = " + str(A[0,0]))

#Sustituir un valor o elemento de la matriz
A[0,1] = 3
A[1,1] = 4
print("=====================================")
print(A)


La posición de la matriz A[2,2] = 12
La posición de la matriz A[0,0] = 3
[[ 3  3  5]
 [17  4 52]
 [ 1  5 12]]


Es posible hacer consultas sobre multiples elementos del arreglo haciendo uso del operador : sobre los índices

In [4]:
print("=====================================")
print("A[0:2, 0] = " + str(A[0:2, 0])) # Caso posición
print("=====================================")
print("A[:,0] = "+str(A[:,0])) # Caso longitud


A[0:2, 0] = [ 3 17]
A[:,0] = [ 3 17  1]


Algunas de las operaciones sencillas de la clase array() de numpy son los siguientes

In [5]:
#Calcular la transpuesta de una matriz
Mt = A.transpose()
print("=====================================")
print("La transpuesta de la matriz A es: \n" + str(Mt))
Mt = A.T
print("=====================================")
print("La transpuesta de la matriz A es: \n" + str(Mt))

#PAra redimensionar una matriz A (conservar los mismos elementos)
Mr = Mt.reshape([9,1])
print("=====================================")
print("Redimensionamiento es: \n" + str(Mr))

La transpuesta de la matriz A es: 
[[ 3 17  1]
 [ 3  4  5]
 [ 5 52 12]]
La transpuesta de la matriz A es: 
[[ 3 17  1]
 [ 3  4  5]
 [ 5 52 12]]
Redimensionamiento es: 
[[ 3]
 [17]
 [ 1]
 [ 3]
 [ 4]
 [ 5]
 [ 5]
 [52]
 [12]]


## 3.- Inicialización avanzada 
Numpy permite crear arreglos de forma predeterminada, incluyendo arreglos de ceros, aleatorios, constantes, o por series

In [6]:
#Para crear matriz de ceros np.zeros((filas, columnas))
z = np.zeros((2,4))
print(f"""
Tamaño de la matriz es
{z.shape}
=====================================
La matriz z es: 
{z}
=====================================
""")

#Para crear matriz de unos np.zeros((filas, columnas))
z1 = np.ones((3,3))
print(f"""
Tamaño de la matriz es
{z1.shape}
=====================================
La matriz z1 es: 
{z1}
=====================================
""")

#Crear el vector lineal (inicio, fin, pasos)
t = np.linspace(0, 15, 10)
print(f"""
Tamaño del vector es
{t.shape}
=====================================
El vector tiempo es: 
{t}
=====================================
""")

#Crear una matriz aleatoria
v2 = np.random.rand(4,4)
print(f"""
Tamaño de la matriz es 
{v2.shape}
=====================================
La matriz v2 es: 
{v2}
=====================================
""")


Tamaño de la matriz es
(2, 4)
La matriz z es: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Tamaño de la matriz es
(3, 3)
La matriz z1 es: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Tamaño del vector es
(10,)
El vector tiempo es: 
[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.         11.66666667 13.33333333 15.        ]


Tamaño de la matriz es 
(4, 4)
La matriz v2 es: 
[[0.92046143 0.66058374 0.38787024 0.33088655]
 [0.08489282 0.3290624  0.03598626 0.48092811]
 [0.38452524 0.37832257 0.05279765 0.99587412]
 [0.96217555 0.85221544 0.07309373 0.54777477]]



## 4.- Operaciones con arreglos
Numpy permite hacer operaciones básicas con arreglos tales como suma, resta, producto punto y producto patricial. 

In [7]:
#Crear arreglos aleatorios de 4*1 entre -10 y 10
a = 20*np.random.rand(4,1) - 10
print("a= \n" + str(a))
print("=====================================")

b = 4*np.random.rand(4,1) - 2
print("a= \n" + str(b))
print("=====================================")

c = a+b
print("c= \n" + str(c))
print("=====================================")

d = a*b #Producto elemento a elemento
print("d= \n" + str(d))
print("=====================================")

# e = np.dot(a.T, b) #Producto punto
# print("e= \n" + str(e))
# print("=====================================")

Mr1 = a.reshape([2,2])
print("=====================================")
print("Redimensionamiento de Mr1 es: \n" + str(Mr1))

Mr2 = b.reshape([2,2])
print("=====================================")
print("Redimensionamiento de Mr2 es: \n" + str(Mr2))

f = np.dot(Mr1, Mr2)
print("f= \n" + str(f))
print("=====================================")



a= 
[[ 8.09007646]
 [-7.97200574]
 [-8.2824264 ]
 [ 5.86338601]]
a= 
[[ 0.60809283]
 [ 0.40552935]
 [-1.86379499]
 [ 0.48146923]]
c= 
[[  8.69816929]
 [ -7.56647639]
 [-10.14622139]
 [  6.34485525]]
d= 
[[ 4.91951748]
 [-3.23288231]
 [15.43674482]
 [ 2.82303997]]
Redimensionamiento de Mr1 es: 
[[ 8.09007646 -7.97200574]
 [-8.2824264   5.86338601]]
Redimensionamiento de Mr2 es: 
[[ 0.60809283  0.40552935]
 [-1.86379499  0.48146923]]
f= 
[[ 19.77770182  -0.55751204]
 [-15.96463356  -0.53572703]]


## 5.- Clase linalg 
Numpy provee una clase llamada linalg, que permite hacer operaciones avanzadas de algebra líneal. Como por ejemplo, calcular una inversa

In [8]:
#Inversa de un matriz
Minv = np.linalg.inv(f)
print("La matriz inversa de f es: \n" + str(Minv))
print("=====================================")

print("La operación de f * Minv es: \n" + str(np.dot(f, Minv)))
print("La operación de f * Minv es: \n" + str(f @ Minv) )

La matriz inversa de f es: 
[[ 0.02747892 -0.02859634]
 [-0.81887028 -1.01445312]]
La operación de f * Minv es: 
[[ 1.00000000e+00  3.62253796e-17]
 [-2.83413604e-17  1.00000000e+00]]
La operación de f * Minv es: 
[[ 1.00000000e+00  3.62253796e-17]
 [-2.83413604e-17  1.00000000e+00]]


In [9]:
#La pseudo-inversa
G = np.linalg.pinv(f)
print("La pseudo_inversa de f es: \n" + str(G))
print("=================================")

La pseudo_inversa de f es: 
[[ 0.02747892 -0.02859634]
 [-0.81887028 -1.01445312]]


In [10]:
#Funciones trigonométricas
r = 2*np.sin(35)
print(r)

-0.856365338992302


In [11]:
r2 = np.rad2deg(r)
print(r2)

-49.06611964554894


In [12]:
Q = np.linalg.det(f)
print("El determinante de la matriz f es: \n" + str(Q))

El determinante de la matriz f es: 
-19.495924888872278
